coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 80%

ignore:
  - "*/tests/*"
  - "test_*.py"
  - "util/_typing.py"
  - "util/_testing.py"
