# This file gives the option to use Ruff as a pre-commit hook.
repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.0
  hooks:
    # Run the linter with the fix option enabled.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
