#!/bin/bash

# ----------------------------------------------------------------------------
# Copyright (c) 2013--, scikit-bio development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file COPYING.txt, distributed with this software.
# ----------------------------------------------------------------------------

CONDA_DIR=${PWD}/.conda_test_sandbox
CONDA=${CONDA_DIR}/bin/conda

clean() {
  rm -rf ${CONDA_DIR}
}

install_conda() {
  #wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  chmod +x miniconda.sh
  ./miniconda.sh -b -p ${CONDA_DIR}
  # Update conda itself
  ${CONDA} update --yes conda
}


setup_environment() {
  ${CONDA} create --yes -n ${ENV_NAME} python=$PYTHON_VERSION pip \
    numpy$NUMPY_VERSION scipy matplotlib$MATPLOTLIB_VERSION pandas nose pep8 \
    Sphinx=1.2.2 IPython
  if [ ${USE_CYTHON} ]; then ${CONDA} install --yes -n ${ENV_NAME} cython; fi
  #source activate env_name
  BIN=${CONDA_DIR}/envs/${ENV_NAME}/bin
  ${BIN}/pip install sphinx-bootstrap-theme future \
    six coveralls natsort pyflakes flake8 python-dateutil
}

install() {
  ${BIN}/pip install -e . --no-deps
}

tests() {
  if [ ${WITH_DOCTEST} ]; then 
    PYTHONWARNINGS=ignore ${BIN}/nosetests skbio --with-doctest --with-coverage \
    -I DONOTIGNOREANYTHING 
  else
    PYTHONWARNINGS=ignore ${BIN}/nosetests skbio --with-coverage -I DONOTIGNOREANYTHING
  fi
  ${BIN}/pep8 skbio setup.py checklist.py
  ${BIN}/flake8 skbio setup.py checklist.py
  ./checklist.py
}

run_local() {
  PYTHON_VERSION=3.4
  ENV_NAME=py${PYTHON_VERSION}
  NUMPY_VERSION=
  MATPLOTLIB_VERSION=
}

case "$1" in 
  "tests" )
    tests;;
  "clean" )
    clean;;
  *)
    echo "ERROR"
esac

