# -----------------------------------------------------------------------------
# Copyright (c) 2013--, scikit-bio development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file COPYING.txt, distributed with this software.
# -----------------------------------------------------------------------------
from __future__ import division

import numpy as np

from skbio.core.exception import FastqParseError


def _is_casava_v180_or_later(header_line):
    """ True if this file is generated by Illumina software post-casava 1.8 """
    if not header_line.startswith('@'):
        raise ValueError("Non-header line passed in!")
    fields = header_line.split(':')

    return len(fields) == 10 and fields[7] in 'YN'


def _ascii_to_phred(s, offset):
    """Convert ascii to Phred quality score with specified ASCII offset."""
    return np.fromstring(s, dtype='|S1').view(np.int8) - offset


def _ascii_to_phred33(s):
    """Convert ascii string to Phred quality score with ASCII offset of 33.

    Standard "Sanger" ASCII offset of 33. This is used by Illumina in CASAVA
    versions after 1.8.0, and most other places. Note that internal Illumina
    files still use offset of 64
    """
    return _ascii_to_phred(s, 33)


def _ascii_to_phred64(s):
    """Convert ascii string to Phred quality score with ASCII offset of 64.

    Illumina-specific ASCII offset of 64. This is used by Illumina in CASAVA
    versions prior to 1.8.0, and in Illumina internal formats (e.g.,
    export.txt files).
    """
    return _ascii_to_phred(s, 64)


def _drop_id_marker(s):
    """Drop the first character of str"""
    return s[1:]


def parse_fastq(data, strict=False, force_phred_offset=None):
    r"""yields label, seq, and qual from a fastq file.

    Parameters
    ----------
    data : open file object
        An open fastq file.

    strict : bool
        If strict is true a FastqParse error will be raised if the seq and qual
        labels dont' match.

    force_phred_offset : str or None
        Force a PHRED offset, currently restricted to either '33' or '64'.
        Default behavior is to infer the PHRED offset.

    Returns
    -------
    label, seq, qual : (str, str, np.array)
        yields the label, sequence and quality for each entry

    Examples
    --------
    Assume we have a fastq formatted file with the following contents::

        @seq1
        AACACCAAACTTCTCCACCACGTGAGCTACAAAAG
        +
        ````Y^T]`]c^cabcacc`^Lb^ccYT\T\Y\WF
        @seq2
        TATGTATATATAACATATACATATATACATACATA
        +
        ]KZ[PY]_[YY^```ac^\\`bT``c`\aT``bbb

    We can use the following code:

    >>> from StringIO import StringIO
    >>> from skbio.parse.sequences import parse_fastq
    >>> fastq_f = StringIO('@seq1\n'
    ...                     'AACACCAAACTTCTCCACCACGTGAGCTACAAAAG\n'
    ...                     '+\n'
    ...                     '````Y^T]`]c^cabcacc`^Lb^ccYT\T\Y\WF\n'
    ...                     '@seq2\n'
    ...                     'TATGTATATATAACATATACATATATACATACATA\n'
    ...                     '+\n'
    ...                     ']KZ[PY]_[YY^```ac^\\\`bT``c`\\aT``bbb\n')
    >>> for label, seq, qual in parse_fastq(fastq_f):
    ...     print label
    ...     print seq
    ...     print qual
    seq1
    AACACCAAACTTCTCCACCACGTGAGCTACAAAAG
    [32 32 32 32 25 30 20 29 32 29 35 30 35 33 34 35 33 35 35 32 30 12 34 30 35
     35 25 20 28 20 28 25 28 23  6]
    seq2
    TATGTATATATAACATATACATATATACATACATA
    [29 11 26 27 16 25 29 31 27 25 25 30 32 32 32 33 35 30 28 28 32 34 20 32 32
     35 32 28 33 20 32 32 34 34 34]

    """
    # line number modulus
    SEQUENCEID = 0
    SEQUENCE = 1
    QUALID = 2
    QUAL = 3

    data = iter(data)
    first_line = data.next().strip()

    if force_phred_offset is None:
        if _is_casava_v180_or_later(first_line):
            phred_f = _ascii_to_phred33
        else:
            phred_f = _ascii_to_phred64
    else:
        if force_phred_offset == '33':
            phred_f = _ascii_to_phred33
        elif force_phred_offset == '64':
            phred_f = _ascii_to_phred64
        else:
            raise ValueError("Unknown PHRED offset of %s" % force_phred_offset)

    seqid = _drop_id_marker(first_line)
    seq = None
    qualid = None
    qual = None

    for idx, line in enumerate(data):
        # +1 due to fetch of line prior to loop
        lineno = idx + 1
        linetype = lineno % 4
        line = line.strip()

        if linetype == SEQUENCEID:
            yield seqid, seq, qual

            seqid = _drop_id_marker(line)
            seq = None
            qualid = None
            qual = None
        elif linetype == SEQUENCE:
            seq = line
        elif linetype == QUALID:
            qualid = _drop_id_marker(line)

            if strict:
                if seqid != qualid:
                    raise FastqParseError('Bad record: %s != %s' % (seqid,
                                                                    qualid))
        elif linetype == QUAL:
            qual = phred_f(line)

    # if we did not have a complete record at the end of the data
    if qual is None:
        raise FastqParseError("Incomplete record at the end of data!")
    else:
        yield (seqid, seq, qual)
