"""
BIOM format (:mod:`skbio.io.format.biom`)
=========================================

.. currentmodule:: skbio.io.format.biom

Format Support
--------------
**Has Sniffer: Yes**

Format Specification
--------------------
place holder


Format Parameters
-----------------
place holder

"""

# ----------------------------------------------------------------------------
# Copyright (c) 2013--, scikit-bio development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file COPYING.txt, distributed with this software.
# ----------------------------------------------------------------------------

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import csv

import numpy as np

try:
    import biom as biom_package
    if biom_package.util.HAVE_H5PY:
        import h5py
    else:
        h5py = None

except ImportError:
    biom_package = None

from skbio.io import create_format, BIOMFormatError


biom = create_format('biom')


@biom.sniffer()
def _biom_sniffer(fh):
    return False, {}


@biom.reader(None)
def _biom_to_generator(fh, constructor=None, **kwargs):
    yield None


if biom_package is not None:
    @biom.reader(biom_package.Table)
    def _biom_to_biomtable(fh, **kwargs):
        return biom_package.load_table(fh)

    @biom.writer(biom_package.Table)
    def _biomtable_to_biom(obj, fh):
        if biom_package.util.HAVE_H5PY and fh is h5py.File:
            obj.to_hdf5(fh)
        else:
            fh.write(obj.to_json("generated by scikit-bio"))


@biom.writer(None)
def _generator_to_biom(obj, fh):
    pass
